### ISSUE TITLE
Agent runs, however, Olas rewards are not accumulating. 

### ISSUE THREAD

**Issue by momuntai1** [valory-xyz/olas-operate-app#223]
I just downloaded the latest version of Pearl.  Testing it now.

**Comment by oaksprout** [comment]
Associated logs:
User 1 [pearl_logs-20240709.zip](https://github.com/user-attachments/files/16231433/pearl_logs-20240709.zip)

I've requested logs from 2 further users.

**Comment by oaksprout** [comment]
Logs from another user: 
[pearl_logs_2024-07-15T10_15_32.125Z-0.1.0-rc71.zip](https://github.com/user-attachments/files/16235324/pearl_logs_2024-07-15T10_15_32.125Z-0.1.0-rc71.zip)

**Comment by jmoreira-valory** [comment]
Relevant information observed:

- Version
  - olas_operate_middleware-0.1.0rc47
  - Trader hash `bafybeidok5gwivdabwiuqigy3qzq5ulbw6uqgrlc7aq2ihrazxvil2lxkm` (corresponds to v0.1.0rc62)
- Owner EOA [0x298141d04E165cE0aD1cB355029367672238174C](https://gnosisscan.io/address/0x298141d04E165cE0aD1cB355029367672238174C)
  - :ok: **Balance 1.494466641956429315 xDAI**

- Owner Safe [0xc6B24dFB1Ac16a78BbdD7f9CdF07E3700CBA2Da7](https://gnosisscan.io/address/0xc6B24dFB1Ac16a78BbdD7f9CdF07E3700CBA2Da7)
  - :ok: **Balance 1.799999999999999998 xDAI**
  - Seems to have re-staked several times following service eviction (June 18, 2024 - June 25, 2024 - July 3, 2024 - July 7, 2024 - July 12, 2024).

- Agent EOA [0xF63412060F9D30060a849B369A9d8663649aBFE1](https://gnosisscan.io/address/0xF63412060F9D30060a849B369A9d8663649aBFE1)
  - :ok: **Balance 0.15253610285650467 xDAI**

- Service Safe [0xE0113A139F591efA8Bf5E19308C7C27199682d77](https://gnosisscan.io/address/0xE0113A139F591efA8Bf5E19308C7C27199682d77) has not made any transaction since May 30, 2024
  - :warning: **Service Safe balance 0.00947755104420552 xDAI**
  - Service keeps receiving inactivity warnings and subsequent evictions.
    - Most recent eviction Jul 10, 2024 https://gnosis.blockscout.com/tx/0x4aa667a095d22c97f4f30ca2476ad06c86fb73be09fe4f6d0f1941a1537768b6?tab=logs
    - Staked Jul 12, 2024 https://gnosisscan.io/tx/0xee7f903fa3909594ced30bfec37914de26eeb5d90ec055d67b091cabe90ed484#eventlog
    - Inactivity warning Jul 13, 2024 https://gnosisscan.io/tx/0x16bdcd10f2dc570418fa179b0c6986ee7bf4f82a46ba21d5dd7aa2a8d1c45ac5#eventlog
    - Inactivity warning Jul 14, 2024 https://gnosisscan.io/tx/0x4266405696219305c7e1cfac3f335699c7ddab4348b6adb9249456e75b117e9d#eventlog

The Service Safe balance is less than Mech fee = 0.01 xDAI. For this reason, the agent never manages to make a Mech request and the service gets evicted continuously, therefore not accruing any reward.

The conclusion is that something is not working as expected regarding the funding job for the Service Safe.
Also need to verify if the interface reports this condition correctly, or on the contrary it reports that the agent is working as expected when running and not making transactions.

**Comment by oaksprout** [comment]
@jmoreira-valory this user is additionally reporting an issue that looks similar.

[pearl_logs_2024-07-15T16_39_33.271Z-0.1.0-rc71.zip](https://github.com/user-attachments/files/16237892/pearl_logs_2024-07-15T16_39_33.271Z-0.1.0-rc71.zip)

**Comment by jmoreira-valory** [comment]
Service 508:

Hash is somewhat old `bafybeidok5gwivdabwiuqigy3qzq5ulbw6uqgrlc7aq2ihrazxvil2lxkm` (corresponds to v0.1.0rc62)

- Epoch 24: Accrued rewards
- Epoch 25: Inactivity warning
- Epoch 26: Accrued rewards
- Epoch 27: Accrued rewards
- Epoch 28: Inactivity warning
- Epoch 29: Evicted
- Epoch 30: Inactivity warning
- Epoch 31: Inactivity warning
- Epoch 32: Evicted
- Epoch 33-35: Absent

The agent is not transacting for some reason. Hash seems somewhat old. In the provided logs seems the 'run agent' was not pressed.

**Comment by oaksprout** [comment]
> Relevant information observed (first user, service 486):

This issue has now been resolved for the user – they added more XDAI to their Safe, the agent was auto-funded, and it successfully hit its work target.

There is a related usability issue here though – the user was not aware that the amount in the Safe was below the threshold required to trigger a auto-funding event. I'll create a related issue.

**Comment by oaksprout** [comment]
Further logs from user 2: https://valory-workspace.slack.com/archives/C06HNEWREG3/p1721130636236269?thread_ts=1721059076.130979&cid=C06HNEWREG3

**Comment by jmoreira-valory** [comment]
> Further logs from user 2: https://valory-workspace.slack.com/archives/C06HNEWREG3/p1721130636236269?thread_ts=1721059076.130979&cid=C06HNEWREG3

Based on these logs, the user has an unclosed `aea` process running. It cannot be determined how this happened. The easiest solution is to completely restart the machine and re-open Pearl.
