### ISSUE TITLE
Error deploying service

### ISSUE THREAD

**Issue by adrianoVal** [valory-xyz/olas-operate-app#293]
<img width="535" alt="Screenshot 2024-08-26 at 17 00 57" src="https://github.com/user-attachments/assets/6537bd9b-98ab-4e85-b990-ade75ebd78ff">

[pearl_logs_2024-08-26T13_58_42.350Z-0.1.0-rc117.zip](https://github.com/user-attachments/files/16750334/pearl_logs_2024-08-26T13_58_42.350Z-0.1.0-rc117.zip)

**Comment by truemiller** [comment]
### `debug_data.txt`
- **Issue:** `serviceStatus` is `undefined` and `services` array is empty.
```json
{
  "services": {
    "serviceStatus": "undefined",
    "services": []
  }
}
```
The deployment is failing because the `serviceStatus` is not properly defined, and the `services` array is empty, which indicates that there are no services available to deploy.

### **AgentButton.tsx** (in the frontend codebase)
Deployment is showing failure on the frontend:
```typescript
try {
      await ServicesService.createService({
        stakingProgram: activeStakingProgram ?? defaultStakingProgram, // overwrite with StakingProgram.Alpha to test migration
        serviceTemplate,
        deploy: true,
      });
    } catch (error) {
      console.error(error);
      setServiceStatus(undefined);
      showNotification?.('Error while deploying service');
      setIsServicePollingPaused(false);
      setIsBalancePollingPaused(false);
      return;
    }
```

**Comment by jmoreira-valory** [comment]
The issue happens as follows:
- A service is deployed on-chain
- The app is closed before the service manages to start. Hence, the funding job is not triggered (agent and safe are not funded)
- A service update is triggered.
- The service update process requires that the agent be funded to swap the service Safe owner. Since the funding service has not been called in this particular sequence of actions, the transaction fails.

A fix has been added here https://github.com/valory-xyz/olas-operate-app/pull/234/commits/6c3cb7cbfec52578a6a90a8c336e815263716356 (PR #234)
